# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_stages: [pre-commit]
repos:
  - repo: https://github.com/govuk-one-login/pre-commit-hooks.git
    rev: 0.0.1
    hooks:
      - id: terraform-format
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.450
    hooks:
      - id: checkov
        # verbose: true
        args: [--soft-fail, --quiet]